### ISSUE TITLE
Better regex 

### ISSUE THREAD

**Issue by Biromain** [tivie/php-git-log-parser#1]
Hi,
https://github.com/tivie/php-git-log-parser/blob/master/src/Parser.php#L175

`^\[(\S*?)\](.*)`
Without ?, key become `subject][xxx`

**Comment by tivie** [comment]
Hey

Can you please provide an example that isn't working?

**Comment by biromain** [comment]
Commit subject is [Fix #1, #2] My message.
With your actual regex; subject key in array become `subject][Fix ...`

**Comment by 3zzy** [comment]
Ran into the same issue @Biromain 's regex fixed the issue.

**Comment by tivie** [comment]
Should be fixed now
